name: poke # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.9' # just for humans, typically '1.2+git' or '1.3.2'
summary: GNU Poke Binary Editor # 79 char long summary
description: |
  GNU poke is an interactive, extensible editor for binary data. Not limited
  to editing basic entities such as bits and bytes, it provides a full-fledged
  procedural, interactive programming language designed to describe data
  structures and to operate on them.
  http://www.jemarch.net/poke

assumes:
- command-chain

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0
#adopt-info: gnu-poke

# Limit the build impact. I want this thing on my Pi's and my Desktops
# TODO: why doesn't i386 work?
architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64
  - build-on: i386

# icon:

layout:
  /usr/share/poke:
    symlink: $SNAP/usr/share/poke
  /usr/share/tcltk:
    symlink: $SNAP/usr/share/tcltk


plugs:
  dot-files:
    interface: personal-files
    write:
      - $HOME/.pokerc
      - $HOME/.poke_history
      - $HOME/.config/poke
      - $HOME/.poke.d

apps:
  poke:
    command: usr/bin/poke
    command-chain: [bin/symlink-configs.sh]
    plugs:
      - dot-files
      - home
      - network
      - network-bind

  poke-gui:
    command: usr/bin/poke-gui
    command-chain: [bin/symlink-configs.sh]
    # TODO: Write a .desktop file.
    #desktop: <tbd usr/share/applications/poke-gui.desktop>
    plugs:
      - dot-files
      - home
      - network
      - network-bind
      - desktop
      - wayland
      - x11
  pk-elfextractor:
    command: usr/bin/pk-elfextractor
    # Needs a patch


# export SNAPCRAFT_BUILD_ENVIRONMENT_CPU=16
parts:
  home-linkage:
    source: snap/local/sh
    plugin: dump
    organize:
      '*': bin/

  gnu-poke:
    # git clone git://git.savannah.gnu.org/poke.git --recurse-submodules -j8
    # git submodule update --init --recursive
    #source: poke_source/
    source: git://git.savannah.gnu.org/poke.git
    source-tag: releases/poke-0.90
    #  git submodule update --init --recursive
    plugin: autotools
    build-packages:
      - automake
      - autoconf
      - gettext
      - help2man
      - flex
      - libreadline-dev
      - libgc-dev
      - libjson-c-dev
      - tk-dev
      - libnbd-dev
      - texinfo
      - git
      - gawk
    stage-packages:
      - libgc1c2
      - libnbd0
      - libjson-c4
      - tk # for the GUI
      - libtcl8.6 # for the GUI
      - tcllib # for json in the GUI
    after: [gettext, bison]
    # sure would be nice if the poke project bootstrap.conf respected
    # non-default paths. Also, snapcraft only recently got ./bootstrap support,
    # but it doesn't support passing flags to bootstrap yet.
    # One is an upstream bug, another is a downstream feture request.
    # TODO: figure out why snapcraftctl doesn't do anything here.
    override-build: |
      ./bootstrap --gnulib-srcdir=gnulib --jitter-srcdir=jitter --no-git
      ./configure --prefix=/usr --enable-gui --enable-mi
      export MAKEINFOFLAGS="--css-ref=http://www.jemarch.net/homepage.css"
      make -j"${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
      make install DESTDIR="${SNAPCRAFT_PART_INSTALL}"
      make install-html DESTDIR="${SNAPCRAFT_PART_INSTALL}" || true
      make install-pdf DESTDIR="${SNAPCRAFT_PART_INSTALL}" || true
    #  echo "Setting version to '0.1-beta+git-$(git log -n1 --format=%cs-%h)'"
    #  snapcraftctl set-version "0.1-beta+git-$(git log -n1 --format=%cs-%h)"
    # as of 2020-02-14 the /po sub-child of install-pdf is expected to fail,
    # so I trap the failure and say screw it.

  bison:
    source: http://ftp.gnu.org/gnu/bison/bison-3.7.5.tar.xz
    #source: bison-3.7.5_source.tar.xz
    plugin: autotools
    autotools-configure-parameters:
      # move from /usr/local to /usr so the later build steps find the tool
      - --prefix=/usr
      # so the binary can run from ${SNAPCRAFT_STAGE}/usr rather than /usr
      - --enable-relocatable
    prime:
      # put none of these files into the final snap.
      - -*
  gettext:
    source: https://ftp.gnu.org/pub/gnu/gettext/gettext-0.21.tar.gz
    #source: gettext-0.21_source.tar.gz
    plugin: autotools
    autotools-configure-parameters:
      # move from /usr/local to /usr so the later build steps find the tool
      - --prefix=/usr
    prime:
      # put none of these files into the final snap except the lib I think we
      # need.
      - usr/lib/libtextstyle*
